{
 "title": "controller.myOrg.com",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Anka Build Cloud Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live Instance States",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anka_instance_state_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Instance States",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "anka_instance_state_count", "legendFormat": "{{state}}" }
   ]
  },
  { "title": "Anka Build Cloud Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Templates Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anka_registry_template_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Templates Usage (GiB)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anka_registry_template_disk_used / 1024 / 1024 / 1024",
     "legendFormat": "{{template_name}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(anka_registry_disk_free_space/1024/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tags Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by() (anka_registry_template_tags_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tag Disk Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anka_registry_template_tag_disk_used / 1024 / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Template Disk Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(anka_registry_template_disk_used) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Anka Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Instance Count Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(id) (anka_node_instance_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Started Instances (Template Name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max by(template_name) (anka_instance_state_per_template_count{state=\"Started\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anka_node_states_count{state=\"Active\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Node Free Space (GiB)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 19, "y": 23 },
   "targets": [
    {
     "expr": "(anka_node_disk_free_space/1024/1024/1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 12, "w": 2, "x": 22, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "anka_node_states_count{state!=\"Active\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Errored Instances (By Template Name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max by(template_name) (anka_instance_state_per_template_count{state=\"Error\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errored Instances (By Node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(node_uuid) (anka_instance_state_per_node_count{state=\"Error\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}